# Generated by Django 3.0.6 on 2020-06-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia_consulta', models.IntegerField(blank=True, null=True)),
                ('cod_medico', models.IntegerField(blank=True, null=True)),
                ('nome_medico', models.CharField(blank=True, max_length=100, null=True)),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia_consulta', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_exame', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
    ]
