# Generated by Django 3.0.6 on 2020-06-03 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultas',
            new_name='Consulta',
        ),
        migrations.RenameModel(
            old_name='Exames',
            new_name='Exame',
        ),
    ]
