# Generated by Django 3.0.6 on 2020-06-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200602_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='numero_guia_consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='files.Consulta'),
        ),
    ]
