# Generated by Django 3.0.6 on 2020-06-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200603_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exame',
            name='numero_guia_consulta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
